services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db_dev
    ports:
      - "5432:5432"
